In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np


## Testing the companion matrix solver method with numpy

$$(x-2)^2(x+4)(x-3) = x^4 - 3x^3 - 12x^2 - 44x - 48$$

In [30]:
a = np.array([48, -76, 44, -11])
n = a.shape[0]

C = np.concatenate([np.zeros((1,n-1)), np.eye(n-1)], axis=0)
C = np.concatenate([C, np.expand_dims(-a, 1)], axis=1)

print(C)

v, d = np.linalg.eig(C)

[[  0.   0.   0. -48.]
 [  1.   0.   0.  76.]
 [  0.   1.   0. -44.]
 [  0.   0.   1.  11.]]


In [32]:
CC = np.matmul(C, C.T)
d, v = np.linalg.eigh(CC)
print(d)

[  2.27268855e-01   1.00000000e+00   1.00000000e+00   1.01377727e+04]


In [19]:
p = [1, -3, -12, -44, -48]
c = [4, 2, 2, 3]
r = np.poly(c)
print(r)

[  1. -11.  44. -76.  48.]
