In [1]:
import numpy as np
import tensorflow as tf

DTYPE = tf.float64
D = 3
A = tf.get_variable('A', shape = (D,D+1), dtype=DTYPE)

In [3]:
x = tf.placeholder(DTYPE, (D+1,))
X = tf.expand_dims(x, 1)
y = tf.matmul(A, tf.square(X))

H = tf.hessians(y, x)

In [5]:
_x = np.ones((D+1,))
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    _y, _A, _H = sess.run([y, A, H], {x:_x})
    
print('x', _x.shape, _x)
print('y', _y.shape, _y)
print('A', _A.shape, _A)
print('H', len(_H), _H[0].shape, _H)

x (4,) [1. 1. 1. 1.]
y (3, 1) [[ 0.22861923]
 [ 1.13266212]
 [-1.14254537]]
A (3, 4) [[-0.27070308 -0.25762531  0.04333329  0.71361433]
 [ 0.71283419  0.33557694 -0.38563932  0.46989032]
 [-0.76098173 -0.6218379   0.17975771  0.06051655]]
H 1 (4, 4) [array([[-0.63770125, -0.        , -0.        ,  0.        ],
       [-0.        , -1.08777255, -0.        ,  0.        ],
       [-0.        , -0.        , -0.32509664,  0.        ],
       [-0.        , -0.        , -0.        ,  2.48804238]])]


In [4]:
d2ydxx = tf.hessians(y, x)

In [5]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    _d2ydxx = sess.run(d2ydxx, {x:_x})

In [6]:
print(_d2ydxx[0].shape)

(4, 1, 4, 1)


In [7]:
print(len(_d2ydxx))
print(_d2ydxx[0])

1
[[[[-0.27750847]
   [-0.        ]
   [-0.        ]
   [-0.        ]]]


 [[[-0.        ]
   [-0.52915039]
   [-0.        ]
   [-0.        ]]]


 [[[-0.        ]
   [-0.        ]
   [-0.26848726]
   [-0.        ]]]


 [[[-0.        ]
   [-0.        ]
   [-0.        ]
   [-0.7462577 ]]]]
